//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional deadbolt lock.
        /// </summary>
        public static string add_lock_insert {
            get {
                return ResourceManager.GetString("add_lock_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add into card.
        /// </summary>
        public static string addbasket {
            get {
                return ResourceManager.GetString("addbasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Opener.
        /// </summary>
        public static string adde_opener {
            get {
                return ResourceManager.GetString("adde_opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additions:.
        /// </summary>
        public static string additions {
            get {
                return ResourceManager.GetString("additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional Lock.
        /// </summary>
        public static string addlock {
            get {
                return ResourceManager.GetString("addlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на And System.
        /// </summary>
        public static string and_system {
            get {
                return ResourceManager.GetString("and_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на And type of solution.
        /// </summary>
        public static string and_type_of_solution {
            get {
                return ResourceManager.GetString("and_type_of_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cart .
        /// </summary>
        public static string basket {
            get {
                return ResourceManager.GetString("basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Central striker.
        /// </summary>
        public static string centralstrikeradd {
            get {
                return ResourceManager.GetString("centralstrikeradd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change amounts manually.
        /// </summary>
        public static string changeqty {
            get {
                return ResourceManager.GetString("changeqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose 1 leaf or 2 leaf.
        /// </summary>
        public static string choose_leaf {
            get {
                return ResourceManager.GetString("choose_leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Lock Height.
        /// </summary>
        public static string choose_lock_height {
            get {
                return ResourceManager.GetString("choose_lock_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Material of Profile.
        /// </summary>
        public static string choose_material_of_profile {
            get {
                return ResourceManager.GetString("choose_material_of_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Side of Door.
        /// </summary>
        public static string choose_side_of_door {
            get {
                return ResourceManager.GetString("choose_side_of_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item Code.
        /// </summary>
        public static string column_code {
            get {
                return ResourceManager.GetString("column_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string column_description {
            get {
                return ResourceManager.GetString("column_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string column_qty {
            get {
                return ResourceManager.GetString("column_qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на configurator for.
        /// </summary>
        public static string configurator_for {
            get {
                return ResourceManager.GetString("configurator_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Opener.
        /// </summary>
        public static string e_opener {
            get {
                return ResourceManager.GetString("e_opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latch slide for E-Opener.
        /// </summary>
        public static string e_opener_latchslide {
            get {
                return ResourceManager.GetString("e_opener_latchslide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mechanical E-opener.
        /// </summary>
        public static string e_opener_mechanical {
            get {
                return ResourceManager.GetString("e_opener_mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Opener Options.
        /// </summary>
        public static string e_opener_options {
            get {
                return ResourceManager.GetString("e_opener_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reversive E-opener 12V.
        /// </summary>
        public static string e_opener_reversive_12v {
            get {
                return ResourceManager.GetString("e_opener_reversive_12v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reversive E-opener 24V.
        /// </summary>
        public static string e_opener_reversive_24v {
            get {
                return ResourceManager.GetString("e_opener_reversive_24v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Opener 10-24V (Standard).
        /// </summary>
        public static string e_opener_standard {
            get {
                return ResourceManager.GetString("e_opener_standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Espagnolette bolt for inactive leaf.
        /// </summary>
        public static string espagnolette_bolt {
            get {
                return ResourceManager.GetString("espagnolette_bolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to PDF.
        /// </summary>
        public static string exportpdf {
            get {
                return ResourceManager.GetString("exportpdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension.
        /// </summary>
        public static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Striker for up/down locks and extension lock.
        /// </summary>
        public static string extensionadd1 {
            get {
                return ResourceManager.GetString("extensionadd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Striker for up/down locks.
        /// </summary>
        public static string extensionadd2 {
            get {
                return ResourceManager.GetString("extensionadd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Striker for extension lock.
        /// </summary>
        public static string extensionstrikeradd {
            get {
                return ResourceManager.GetString("extensionstrikeradd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FUHR lock systems..
        /// </summary>
        public static string fuhr_lock_systems {
            get {
                return ResourceManager.GetString("fuhr_lock_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function:.
        /// </summary>
        public static string function {
            get {
                return ResourceManager.GetString("function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting Started.
        /// </summary>
        public static string getting_started {
            get {
                return ResourceManager.GetString("getting_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap header {
            get {
                object obj = ResourceManager.GetObject("header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height:.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inside/Outside:.
        /// </summary>
        public static string inside_outside {
            get {
                return ResourceManager.GetString("inside_outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock.
        /// </summary>
        public static string lock_add {
            get {
                return ResourceManager.GetString("lock_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock Series and Type, Lock Side.
        /// </summary>
        public static string lock_series_type_side {
            get {
                return ResourceManager.GetString("lock_series_type_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Material of profile:.
        /// </summary>
        public static string material_of_profile {
            get {
                return ResourceManager.GetString("material_of_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next Step.
        /// </summary>
        public static string next_step_btn {
            get {
                return ResourceManager.GetString("next_step_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One Piece or Single:.
        /// </summary>
        public static string one_piece_or_single {
            get {
                return ResourceManager.GetString("one_piece_or_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One Piece Striker.
        /// </summary>
        public static string onepiecestrikeradd {
            get {
                return ResourceManager.GetString("onepiecestrikeradd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Order Number:.
        /// </summary>
        public static string ordernumber {
            get {
                return ResourceManager.GetString("ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result for system:.
        /// </summary>
        public static string result_for_system {
            get {
                return ResourceManager.GetString("result_for_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rod guide.
        /// </summary>
        public static string rod_guide {
            get {
                return ResourceManager.GetString("rod_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round rod 2000mm.
        /// </summary>
        public static string round_rod_2000 {
            get {
                return ResourceManager.GetString("round_rod_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round rod 2500mm.
        /// </summary>
        public static string round_rod_2500 {
            get {
                return ResourceManager.GetString("round_rod_2500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round rod 3000mm.
        /// </summary>
        public static string round_rod_3000 {
            get {
                return ResourceManager.GetString("round_rod_3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock Series:.
        /// </summary>
        public static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Side:.
        /// </summary>
        public static string side {
            get {
                return ResourceManager.GetString("side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solution:.
        /// </summary>
        public static string solution {
            get {
                return ResourceManager.GetString("solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Again.
        /// </summary>
        public static string start_again_btn {
            get {
                return ResourceManager.GetString("start_again_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Striker for additional deadbolt lock.
        /// </summary>
        public static string striker_for_addlock {
            get {
                return ResourceManager.GetString("striker_for_addlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System:.
        /// </summary>
        public static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Threshold strike plate.
        /// </summary>
        public static string threshold_strike_plate {
            get {
                return ResourceManager.GetString("threshold_strike_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type:.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upper Bolt Striker.
        /// </summary>
        public static string upperboltstriker {
            get {
                return ResourceManager.GetString("upperboltstriker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to.
        /// </summary>
        public static string welcome_to {
            get {
                return ResourceManager.GetString("welcome_to", resourceCulture);
            }
        }
    }
}
